numaproj/numalogic-prometheus

README.md
deployment/mlflow-deployment.yaml
deployment/numalogic-prometheus-pipeline.yaml
deployment/numalogic-training-workflow-template.yaml

Signed-off-by: nkoppisetty <nandita.iitkgp@gmail.com>

docs: updating read me

---

pyproject.toml

Signed-off-by: Avik Basu <avikbasu93@gmail.com>

chore: bump to v0.0.3

---

.github/workflows/ci.yml

Signed-off-by: nkoppisetty <nandita.iitkgp@gmail.com>
Fixing indentation in ci.yml

fix: indentation

---

.github/workflows/ci.yml
.github/workflows/coverage.yml
numaprom/constants.py

chore: build changes

---

manifests/kustomization.yaml
manifests/pipeline/numalogic-prometheus-pipeline.yaml
manifests/prerequisites/kustomization.yaml

Signed-off-by: nkoppisetty <nandita.iitkgp@gmail.com>

chore: manifests

---

manifests/pipeline/numalogic-prometheus-pipeline.yaml
manifests/prerequisites/argoworkflows/kustomization.yaml
manifests/prerequisites/numaflow/kustomization.yaml

Signed-off-by: nkoppisetty <nandita.iitkgp@gmail.com>

fix: manifests

---

.github/workflows/ci.yml

fix: build ci typo

---

Dockerfile
poetry.lock
pyproject.toml

Reduces the image size from 4.26GB to 1.66GB

fix: docker image size

---

.github/workflows/ci.yml

fix: tag for release

---

Dockerfile
pyproject.toml

fix: install pytorch-lightning in docker

---

.github/workflows/ci.yml

fix: branch name

---

.github/workflows/ci.yml

fix: build

---

numaprom/_constants.py
numaprom/factory.py
numaprom/tools.py
numaprom/udf/inference.py
numaprom/udsink/__init__.py
numaprom/udsink/train_rollout.py
pyproject.toml
tests/__init__.py
tests/test_factory.py
tests/test_trainer.py

- Introduce rollouts anomaly
- pass uuid to trainer payload
- avoid logging as error when model is not found (404)

feat: rollouts anomaly

---

numaprom/_constants.py
tests/tools.py

chore: add configuration for fuzzy metrics

---

numaprom/udsink/train_rollout.py
poetry.lock
pyproject.toml

chore: bump version

---

numaprom/udsink/train_rollout.py

fix: avoid setting as failure in udsink

---

.flake8
numaprom/_constants.py
numaprom/prometheus.py
numaprom/tools.py
numaprom/udf/inference.py
numaprom/udf/postprocess.py
numaprom/udf/preprocess.py
numaprom/udf/window.py
numaprom/udsink/train.py
numaprom/udsink/train_rollout.py
pyproject.toml
tests/test_trainer.py
tests/tools.py
tests/udf/test_inference.py

chore: unified anomaly

---

numaprom/udf/threshold.py
numaprom/udsink/train.py
numaprom/udsink/train_rollout.py
pyproject.toml

fix: train threshold clf

---

numaprom/entities.py
numaprom/udf/preprocess.py
numaprom/udf/window.py
pyproject.toml
tests/resources/data/stream_nan.json
tests/udf/test_preprocess.py

- converts NaN, +Inf and -Inf to 0.0

fix: cleaning nan & inf values to 0.0

---

docs/metrics.md
numaprom/_constants.py
numaprom/tools.py
numaprom/udf/postprocess.py
numaprom/udsink/train.py
numaprom/udsink/train_rollout.py
pyproject.toml
tests/tools.py
tests/udf/test_postprocess.py

1. Added config for fuzzy prod metrics
2. Refactored config structure a little, added output_config

chore: adding config for fuzzy prod

---

numaprom/_constants.py
pyproject.toml

fix: metric name for fuzzy error rate

---

numaprom/udf/postprocess.py
pyproject.toml

fix: logging bug

---

numaprom/_constants.py
numaprom/udf/postprocess.py
pyproject.toml

fix: metric name

---

numaprom/udf/inference.py
pyproject.toml

fix: remove log

---

.github/workflows/release-go.yaml

fix: Fix the release repo for prometheus-serde

---

.github/workflows/release-go.yaml

fix: Fix the quay.io repo

---

pyproject.toml

chore: bump version to v0.1.5

---

numaprom/config/__init__.py
numaprom/config/_config.py
numaprom/entities.py
numaprom/tools.py
numaprom/udf/postprocess.py
numaprom/udf/threshold.py
numaprom/udf/window.py
numaprom/udsink/train_rollout.py
poetry.lock
pyproject.toml
tests/resources/config.yaml
tests/resources/default_numalogic.yaml
tests/udf/test_postprocess.py

- Enable ensemble scoring
- Add static_threshold_wt field in config
- Increase min training datapoints to 1000 -> 2000
- Increase threshold factor 3 -> 5 to make the model less sensitive
- Use TanhScaler as default preprocessing step

feat: ensemble scoring

---

numaprom/config/default/numalogic.yaml
numaprom/udf/postprocess.py
numaprom/udsink/train.py
numaprom/udsink/train_rollout.py
poetry.lock
pyproject.toml

1. Updated main, preprocess and threshold model trainers to use config
2. Updated postprocess to use config, and generate max/weighted unified score

feat: config driven trainers

---

numaprom/tools.py
numaprom/udf/inference.py
pyproject.toml
tests/tools.py

fix: import bugs

---

numaprom/tools.py
numaprom/udf/inference.py
numaprom/udf/preprocess.py
numaprom/udf/threshold.py
numaprom/udsink/train_rollout.py
poetry.lock
pyproject.toml
tests/__init__.py
tests/test_trainer.py
tests/udf/test_inference.py
tests/udf/test_postprocess.py
tests/udf/test_preprocess.py
tests/udf/test_threshold.py

- attempt to refresh the session

fix: update default session for aws

---

numaprom/tools.py
numaprom/udf/preprocess.py
numaprom/udf/threshold.py
numaprom/udsink/train_rollout.py
pyproject.toml

- save & load preproc & thresh models using conf names
- save train size as artifact params

fix: save preproc + thresh model with conf keys

---

poetry.lock
pyproject.toml

fix: tanh scaler nan bug

---

pyproject.toml

chore: bumping version

---

numaprom/__init__.py
numaprom/clients/prometheus.py
numaprom/udf/preprocess.py
numaprom/udf/threshold.py
poetry.lock
pyproject.toml
tests/udf/test_preprocess.py
tests/udf/test_threshold.py

Fix exception handling while loading pickle models

Fix exception

---

manifests/prerequisites/prometheus/install.yaml

Update prometheus install.yaml

---

manifests/pipeline/install-numalogic-rollouts.yaml
manifests/prerequisites/prometheus/install.yaml
manifests/prerequisites/prometheus/prometheus-rules.yaml

Manifest 1
